"""
hid_shield.security.policy_engine
====================================
Rule-based device risk evaluator for HID Shield.

Architecture
------------
``PolicyEngine`` loads its rules from ``config.yaml → policy`` on construction
and applies them to device data dictionaries (or ``DeviceEvent`` ORM objects)
to produce:

* A ``RiskLevel`` classification (SAFE / LOW / MEDIUM / HIGH / CRITICAL).
* A ``PolicyAction`` recommendation (allow / block / prompt / monitor).

Rule ordering (higher rules take precedence, evaluated top-to-bottom):

1. **Entropy threshold** – if the keystroke-entropy score exceeds the
   configured threshold → HIGH or CRITICAL risk.
2. **Keystroke rate** – if keystrokes-per-second exceeds the configured
   limit → MEDIUM or HIGH risk.
3. **Suspicious file count** – if the device event carries file-scan results
   with malicious files → escalate risk accordingly.
4. **Unknown serial** – devices without a serial number get LOW risk by
   default (may be escalated by other rules).
5. **Default action fallback** – uses the ``policy.default_action`` setting.

All thresholds are fully configurable without code changes.

Simulation mode
---------------
In simulation mode the engine logs every evaluation so developers can trace
risk decisions in the console.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

import yaml


# ---------------------------------------------------------------------------
# Configuration helpers
# ---------------------------------------------------------------------------

_HERE: Path = Path(__file__).resolve().parent
_PROJECT_ROOT: Path = _HERE.parent
_CONFIG_PATH: Path = _PROJECT_ROOT / "config.yaml"


def _load_config() -> dict[str, Any]:
    if _CONFIG_PATH.exists():
        with open(_CONFIG_PATH, "r", encoding="utf-8") as fh:
            return yaml.safe_load(fh) or {}
    return {}


def _is_simulation_mode() -> bool:
    env_val = os.getenv("HID_SHIELD_SIMULATION_MODE", "").lower()
    if env_val in ("true", "1", "yes"):
        return True
    if env_val in ("false", "0", "no"):
        return False
    return bool(_load_config().get("simulation_mode", False))


# ---------------------------------------------------------------------------
# Inline risk / action constants (avoid circular import with models.py)
# ---------------------------------------------------------------------------

# Risk levels (string literals matching database.models.RiskLevel)
RISK_SAFE: str = "safe"
RISK_LOW: str = "low"
RISK_MEDIUM: str = "medium"
RISK_HIGH: str = "high"
RISK_CRITICAL: str = "critical"

# Policy actions (string literals matching database.models.PolicyAction)
ACTION_ALLOW: str = "allow"
ACTION_BLOCK: str = "block"
ACTION_QUARANTINE: str = "quarantine"
ACTION_PROMPT: str = "prompt"
ACTION_MONITOR: str = "monitor"

# Map risk level → integer rank (used for comparisons)
_RISK_RANK: dict[str, int] = {
    RISK_SAFE: 0,
    RISK_LOW: 1,
    RISK_MEDIUM: 2,
    RISK_HIGH: 3,
    RISK_CRITICAL: 4,
}


# ---------------------------------------------------------------------------
# Typed device snapshot passed to the engine
# ---------------------------------------------------------------------------


@dataclass
class DeviceSnapshot:
    """A lightweight, typed view of a USB device event used by the engine.

    Callers populate this from a raw OS event, a ``DeviceEvent`` ORM object,
    or a simulation harness.  Fields default to ``None`` / ``False`` / ``0``
    so partial data is always safe to pass.

    Attributes
    ----------
    device_name:
        Human-readable device name.
    vendor_id, product_id:
        USB VID/PID hex strings.
    serial:
        USB serial number (``None`` or empty = unknown).
    manufacturer:
        Manufacturer string.
    device_type:
        Device category string (keyboard / mouse / storage / …).
    entropy_score:
        Keystroke-entropy in [0.0, 1.0].  ``None`` = not measured.
    keystroke_rate:
        Keystrokes per second.  ``None`` = not measured.
    malicious_file_count:
        Number of files flagged as malicious in associated scans.
    total_file_count:
        Total files seen on a storage device.
    is_simulated:
        True when generated by the simulation engine.
    extra:
        Catch-all dict for future rule attributes.
    """
    device_name: str = "Unknown Device"
    vendor_id: Optional[str] = None
    product_id: Optional[str] = None
    serial: Optional[str] = None
    manufacturer: Optional[str] = None
    device_type: str = "unknown"
    entropy_score: Optional[float] = None
    keystroke_rate: Optional[float] = None
    malicious_file_count: int = 0
    total_file_count: int = 0
    is_simulated: bool = False
    extra: dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Evaluation result
# ---------------------------------------------------------------------------


@dataclass
class EvaluationResult:
    """The output of a ``PolicyEngine.evaluate()`` call.

    Attributes
    ----------
    risk_level:
        Computed risk level string (``RISK_*`` constant).
    recommended_action:
        Recommended policy action string (``ACTION_*`` constant).
    triggered_rules:
        List of human-readable descriptions of rules that fired.
    confidence:
        Aggregate confidence score in [0.0, 1.0] (higher = more certain).
    """
    risk_level: str = RISK_LOW
    recommended_action: str = ACTION_PROMPT
    triggered_rules: list[str] = field(default_factory=list)
    confidence: float = 0.5

    def is_high_risk(self) -> bool:
        """Return ``True`` if risk is HIGH or CRITICAL."""
        return _RISK_RANK.get(self.risk_level, 0) >= _RISK_RANK[RISK_HIGH]

    def __str__(self) -> str:
        rules = "; ".join(self.triggered_rules) or "none"
        return (
            f"EvaluationResult(risk={self.risk_level}, "
            f"action={self.recommended_action}, "
            f"rules=[{rules}], confidence={self.confidence:.2f})"
        )


# ---------------------------------------------------------------------------
# PolicyEngine
# ---------------------------------------------------------------------------


class PolicyEngine:
    """Rule-based device risk evaluator.

    Parameters
    ----------
    config_override:
        Optional ``policy`` section dict to use instead of loading from the
        YAML file.  Useful for unit tests.
    simulation_mode:
        Override the simulation flag from config.

    Examples
    --------
    .. code-block:: python

        from security.policy_engine import PolicyEngine, DeviceSnapshot

        pe = PolicyEngine()
        result = pe.evaluate(DeviceSnapshot(
            device_name="Shady Stick",
            device_type="keyboard",
            entropy_score=0.91,
            keystroke_rate=120.0,
        ))
        print(result)
    """

    def __init__(
        self,
        config_override: Optional[dict[str, Any]] = None,
        simulation_mode: Optional[bool] = None,
    ) -> None:
        config: dict[str, Any] = _load_config()
        policy_cfg: dict[str, Any] = config_override or config.get("policy", {})
        self.simulation_mode: bool = (
            simulation_mode if simulation_mode is not None else _is_simulation_mode()
        )

        # --- Thresholds (all configurable) ---

        #: Entropy score above which the device is flagged as suspicious.
        self.entropy_threshold: float = float(
            policy_cfg.get("entropy_threshold", 0.65)
        )
        #: Entropy score above which the device is considered critically dangerous.
        self.entropy_critical: float = float(
            policy_cfg.get("entropy_critical", 0.90)
        )

        #: Keystrokes-per-second above which the device is suspicious.
        self.max_keystroke_rate: float = float(
            policy_cfg.get("max_keystroke_rate", 80)
        )
        #: KPS above which the risk escalates to HIGH (rubber-ducky level).
        self.critical_keystroke_rate: float = float(
            policy_cfg.get("critical_keystroke_rate", 200)
        )

        #: How many malicious files trigger a CRITICAL rating on storage devices.
        self.critical_malicious_file_count: int = int(
            policy_cfg.get("critical_malicious_file_count", 3)
        )

        #: Default action when no other rule fires.
        self.default_action: str = str(
            policy_cfg.get("default_action", ACTION_PROMPT)
        )

        #: Whether to automatically block flagged devices without prompting.
        self.auto_block_high_risk: bool = bool(
            policy_cfg.get("auto_block_high_risk", False)
        )
        #: Same for CRITICAL devices.
        self.auto_block_critical: bool = bool(
            policy_cfg.get("auto_block_critical", True)
        )

        if self.simulation_mode:
            print(
                "[POLICY] PolicyEngine initialised in SIMULATION_MODE — "
                f"entropy_threshold={self.entropy_threshold}, "
                f"max_keystroke_rate={self.max_keystroke_rate}"
            )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def evaluate(self, device: DeviceSnapshot) -> EvaluationResult:
        """Run all rules against a ``DeviceSnapshot`` and return a result.

        Rules are evaluated in priority order.  The highest risk level found
        by any rule wins.  The recommended action is derived from that risk
        level using the configured policy.

        Parameters
        ----------
        device:
            The device data to evaluate.

        Returns
        -------
        EvaluationResult
            Risk classification, recommended action, and triggered rules.
        """
        result = EvaluationResult(
            risk_level=RISK_LOW,
            recommended_action=self.get_default_action(),
        )

        # Accumulate the highest risk found across all rules
        current_rank: int = _RISK_RANK[RISK_LOW]

        def _escalate(new_level: str, rule_description: str) -> None:
            """Update result if new_level is higher than current."""
            nonlocal current_rank
            new_rank = _RISK_RANK.get(new_level, 0)
            result.triggered_rules.append(rule_description)
            if new_rank > current_rank:
                current_rank = new_rank
                result.risk_level = new_level

        # --- Rule 1: Entropy ---
        if device.entropy_score is not None:
            if device.entropy_score >= self.entropy_critical:
                _escalate(
                    RISK_CRITICAL,
                    f"Entropy {device.entropy_score:.3f} ≥ critical "
                    f"threshold {self.entropy_critical}",
                )
                result.confidence = min(1.0, device.entropy_score + 0.05)
            elif device.entropy_score >= self.entropy_threshold:
                _escalate(
                    RISK_HIGH,
                    f"Entropy {device.entropy_score:.3f} ≥ threshold "
                    f"{self.entropy_threshold}",
                )
                result.confidence = device.entropy_score

        # --- Rule 2: Keystroke rate ---
        if device.keystroke_rate is not None:
            if device.keystroke_rate >= self.critical_keystroke_rate:
                _escalate(
                    RISK_CRITICAL,
                    f"Keystroke rate {device.keystroke_rate:.1f} KPS ≥ "
                    f"critical limit {self.critical_keystroke_rate}",
                )
            elif device.keystroke_rate >= self.max_keystroke_rate:
                _escalate(
                    RISK_HIGH,
                    f"Keystroke rate {device.keystroke_rate:.1f} KPS ≥ "
                    f"limit {self.max_keystroke_rate}",
                )

        # --- Rule 3: Malicious files ---
        if device.malicious_file_count > 0:
            if device.malicious_file_count >= self.critical_malicious_file_count:
                _escalate(
                    RISK_CRITICAL,
                    f"{device.malicious_file_count} malicious files detected "
                    f"(threshold: {self.critical_malicious_file_count})",
                )
            else:
                _escalate(
                    RISK_HIGH,
                    f"{device.malicious_file_count} malicious file(s) detected",
                )
            result.confidence = min(1.0, result.confidence + 0.2)

        # --- Rule 4: No serial number (low-confidence escalation) ---
        if not device.serial:
            if current_rank < _RISK_RANK[RISK_MEDIUM]:
                _escalate(
                    RISK_LOW,
                    "Device has no serial number (identity unverifiable)",
                )

        # --- Rule 5: Unknown device type ---
        if device.device_type == "unknown":
            if current_rank < _RISK_RANK[RISK_MEDIUM]:
                _escalate(
                    RISK_LOW,
                    "Device type is unknown / unclassified",
                )

        # --- Derive the recommended action from the final risk level ---
        result.recommended_action = self._action_for_risk(result.risk_level)

        if self.simulation_mode:
            print(
                f"[POLICY] evaluate({device.device_name!r}) → {result}"
            )

        return result

    def evaluate_device_risk_level(self, device: DeviceSnapshot) -> str:
        """Convenience wrapper — return only the risk level string.

        Parameters
        ----------
        device:
            Device snapshot to evaluate.

        Returns
        -------
        str
            One of the ``RISK_*`` constant strings.
        """
        return self.evaluate(device).risk_level

    def should_auto_block(self, device: DeviceSnapshot) -> bool:
        """Return ``True`` if the device should be blocked automatically.

        Uses the configured ``auto_block_high_risk`` and
        ``auto_block_critical`` thresholds.

        Parameters
        ----------
        device:
            Device snapshot to evaluate.

        Returns
        -------
        bool
        """
        result = self.evaluate(device)
        if result.risk_level == RISK_CRITICAL and self.auto_block_critical:
            return True
        if result.risk_level == RISK_HIGH and self.auto_block_high_risk:
            return True
        return False

    def get_default_action(self) -> str:
        """Return the configured default policy action string.

        Returns
        -------
        str
            One of ``"allow"``, ``"block"``, ``"prompt"``, ``"monitor"``,
            or ``"quarantine"``.
        """
        return self.default_action

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _action_for_risk(self, risk_level: str) -> str:
        """Map a risk level to the appropriate policy action.

        The mapping respects the ``auto_block_*`` configuration flags.

        Parameters
        ----------
        risk_level:
            One of the ``RISK_*`` constants.

        Returns
        -------
        str
            The recommended ``ACTION_*`` constant.
        """
        match risk_level:
            case "critical":
                return ACTION_BLOCK if self.auto_block_critical else ACTION_PROMPT
            case "high":
                return ACTION_BLOCK if self.auto_block_high_risk else ACTION_PROMPT
            case "medium":
                return ACTION_MONITOR
            case "low":
                return self.default_action
            case "safe":
                if self.default_action in {ACTION_BLOCK, ACTION_QUARANTINE, ACTION_PROMPT}:
                    return self.default_action
                return ACTION_ALLOW
            case _:
                return self.default_action

    def describe_rules(self) -> list[str]:
        """Return a human-readable description of all active rules.

        Useful for displaying policy settings in the admin UI.

        Returns
        -------
        list[str]
            One string per active rule.
        """
        return [
            f"Entropy threshold: {self.entropy_threshold} "
            f"(critical: {self.entropy_critical})",
            f"Max keystroke rate: {self.max_keystroke_rate} KPS "
            f"(critical: {self.critical_keystroke_rate})",
            f"Malicious file threshold: {self.critical_malicious_file_count} file(s)",
            f"Default action: {self.default_action}",
            f"Auto-block critical: {self.auto_block_critical}",
            f"Auto-block high risk: {self.auto_block_high_risk}",
        ]
