"""
hid_shield.core.device_info
=============================
Data models representing a live USB device as detected by the OS.

Design
------
* Clean separation from the SQLAlchemy ``DeviceEvent`` model.  This is a
  transient representation of hardware state, whereas the ORM model represents
  a captured historical event.
* Provides helper methods to cast the hardware attributes into dictionaries
  suitable for PySide6 Signal payloads.
"""

from __future__ import annotations

import uuid
from dataclasses import asdict, dataclass, field
from typing import Any, Optional


@dataclass
class DeviceInfo:
    """Represents a physical USB device detected by the OS monitor.

    Attributes
    ----------
    device_id:
        A unique hardware path or generated UUID for this connection instance.
    device_name:
        Human-readable descriptor (e.g. "Logitech G502 Mouse").
    vendor_id:
        4-hex-digit string (VID).
    product_id:
        4-hex-digit string (PID).
    serial_number:
        USB serial number string if available.
    manufacturer:
        String reported by the device descriptor.
    device_type:
        Broad category ("keyboard", "mouse", "storage", "composite", "unknown").
    is_simulated:
        True if generated by the simulation engine rather than real hardware.
    capacity_bytes:
        For storage devices, total capacity in bytes (0 if not applicable).
    raw_properties:
        A dictionary of all OS-specific properties (WMI / udev attributes)
        useful for forensic logging.
    """

    device_id: str = field(default_factory=lambda: uuid.uuid4().hex)
    device_name: str = "Unknown Device"
    vendor_id: Optional[str] = None
    product_id: Optional[str] = None
    serial_number: Optional[str] = None
    manufacturer: Optional[str] = None
    device_type: str = "unknown"
    is_simulated: bool = False
    capacity_bytes: int = 0
    raw_properties: dict[str, Any] = field(default_factory=dict)

    @property
    def name(self) -> str:
        """Compatibility alias used by legacy tests and console scripts."""
        return self.device_name

    def to_dict(self) -> dict[str, Any]:
        """Serialize the dataclass to a basic dictionary for PyQt/PySide signals.

        Returns
        -------
        dict[str, Any]
        """
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> DeviceInfo:
        """Reconstruct a DeviceInfo object from a dictionary payload.

        Parameters
        ----------
        data:
            Dictionary mapped to the dataclass fields.

        Returns
        -------
        DeviceInfo
        """
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})

    def get_hardware_id(self) -> str:
        """Return the standard Windows-style HWID string.

        Format: USB\\VID_xxxx&PID_yyyy

        Returns
        -------
        str
        """
        vid = (self.vendor_id or "0000").upper()
        pid = (self.product_id or "0000").upper()
        return f"USB\\VID_{vid}&PID_{pid}"

    @classmethod
    def fake_device(cls) -> "DeviceInfo":
        """Create a deterministic simulated USB device for test harnesses."""
        return cls(
            device_name="Simulated USB Composite Device",
            vendor_id="1209",
            product_id="0001",
            serial_number="SIM-HID-0001",
            manufacturer="HID Shield Lab",
            device_type="composite",
            is_simulated=True,
            capacity_bytes=64_000_000,
            raw_properties={"source": "fake_device", "confidence": "high"},
        )
