"""
hid_shield.database.repository
================================
Repository (CRUD helper) classes for each ORM model.

Design decisions
----------------
* All methods are ``@classmethod`` so the classes can be used without
  instantiation, keeping call-sites concise:
  ``DeviceRepository.create_event(session, ...)``.
* Every method that writes to the database accepts an explicit ``Session``
  argument so the caller controls transaction scope (typically via ``get_db``).
* Read methods accept an optional ``session`` parameter — when one is
  provided it is reused; otherwise the method opens its own via ``get_db()``.
* No global state is held; the classes are pure stateless helper namespaces.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import desc, func, select
from sqlalchemy.orm import Session

from database.db import get_db
from database.models import (
    AlertCategory,
    AlertSeverity,
    DeviceEvent,
    DeviceType,
    FileScanResult,
    PolicyAction,
    RiskLevel,
    SystemAlert,
    UserAction,
)


# ---------------------------------------------------------------------------
# DeviceRepository
# ---------------------------------------------------------------------------


class DeviceRepository:
    """CRUD operations for the ``DeviceEvent`` table.

    All write methods require an explicit ``Session`` so the caller can group
    multiple operations in a single transaction.

    Examples
    --------
    .. code-block:: python

        from database.db import get_db
        from database.repository import DeviceRepository

        with get_db() as session:
            event = DeviceRepository.create_event(
                session,
                device_name="SuspiciousKB",
                risk_level=RiskLevel.HIGH,
                action_taken=PolicyAction.BLOCK,
            )
    """

    @classmethod
    def create_event(
        cls,
        session: Session,
        *,
        device_name: str = "Unknown Device",
        vendor_id: Optional[str] = None,
        product_id: Optional[str] = None,
        serial: Optional[str] = None,
        manufacturer: Optional[str] = None,
        device_type: DeviceType | str = DeviceType.UNKNOWN,
        risk_level: RiskLevel | str = RiskLevel.LOW,
        entropy_score: Optional[float] = None,
        keystroke_rate: Optional[float] = None,
        action_taken: PolicyAction | str = PolicyAction.PROMPT,
        is_simulated: bool = False,
        notes: Optional[str] = None,
    ) -> DeviceEvent:
        """Create and persist a new ``DeviceEvent`` row.

        Parameters
        ----------
        session:
            An active SQLAlchemy session (from ``get_db()``).
        device_name:
            Human-readable name of the device.
        vendor_id, product_id:
            USB VID / PID as 4-hex-digit strings.
        serial:
            USB serial number string.
        manufacturer:
            USB manufacturer string.
        device_type:
            ``DeviceType`` enum value or its string equivalent.
        risk_level:
            ``RiskLevel`` enum value or its string equivalent.
        entropy_score:
            Keystroke-entropy score in [0.0, 1.0].
        keystroke_rate:
            Observed keystrokes per second.
        action_taken:
            ``PolicyAction`` applied to this event.
        is_simulated:
            True when generated by the simulation engine.
        notes:
            Free-text analyst notes.

        Returns
        -------
        DeviceEvent
            The newly created (and flushed) ``DeviceEvent`` instance.
        """
        # Normalise enum values — accept both enum member and raw string
        device_type_val: str = (
            device_type.value if isinstance(device_type, DeviceType) else device_type
        )
        risk_level_val: str = (
            risk_level.value if isinstance(risk_level, RiskLevel) else risk_level
        )
        action_val: str = (
            action_taken.value if isinstance(action_taken, PolicyAction) else action_taken
        )

        event = DeviceEvent(
            device_name=device_name,
            vendor_id=vendor_id,
            product_id=product_id,
            serial=serial,
            manufacturer=manufacturer,
            device_type=device_type_val,
            risk_level=risk_level_val,
            entropy_score=entropy_score,
            keystroke_rate=keystroke_rate,
            action_taken=action_val,
            is_simulated=is_simulated,
            notes=notes,
            timestamp=datetime.now(timezone.utc),
        )
        session.add(event)
        session.flush()   # Populate auto-generated ``id`` without committing
        return event

    @classmethod
    def get_event_by_id(
        cls,
        event_id: int,
        session: Optional[Session] = None,
    ) -> Optional[DeviceEvent]:
        """Fetch a single ``DeviceEvent`` by primary key.

        Parameters
        ----------
        event_id:
            The integer primary key of the event.
        session:
            Optional existing session; opens a new one if not provided.

        Returns
        -------
        DeviceEvent or None
        """
        if session is not None:
            return session.get(DeviceEvent, event_id)

        with get_db() as s:
            return s.get(DeviceEvent, event_id)

    @classmethod
    def get_recent_events(
        cls,
        limit: int = 50,
        session: Optional[Session] = None,
    ) -> list[DeviceEvent]:
        """Return the most recent ``DeviceEvent`` rows, newest first.

        Parameters
        ----------
        limit:
            Maximum number of rows to return (default 50).
        session:
            Optional existing session.

        Returns
        -------
        list[DeviceEvent]
        """
        stmt = (
            select(DeviceEvent)
            .order_by(desc(DeviceEvent.timestamp))
            .limit(limit)
        )

        if session is not None:
            return list(session.scalars(stmt).all())

        with get_db() as s:
            # Expunge objects so they can be used after the session closes
            rows = list(s.scalars(stmt).all())
            for row in rows:
                s.expunge(row)
            return rows

    @classmethod
    def get_events_by_risk(
        cls,
        risk_level: RiskLevel | str,
        limit: int = 100,
        session: Optional[Session] = None,
    ) -> list[DeviceEvent]:
        """Return events filtered by ``risk_level``, newest first.

        Parameters
        ----------
        risk_level:
            Filter by this risk level.
        limit:
            Maximum rows to return.
        session:
            Optional existing session.
        """
        risk_val: str = (
            risk_level.value if isinstance(risk_level, RiskLevel) else risk_level
        )
        stmt = (
            select(DeviceEvent)
            .where(DeviceEvent.risk_level == risk_val)
            .order_by(desc(DeviceEvent.timestamp))
            .limit(limit)
        )

        if session is not None:
            return list(session.scalars(stmt).all())

        with get_db() as s:
            rows = list(s.scalars(stmt).all())
            for row in rows:
                s.expunge(row)
            return rows

    @classmethod
    def get_high_risk_count(cls, session: Optional[Session] = None) -> int:
        """Return the count of HIGH or CRITICAL risk events.

        Parameters
        ----------
        session:
            Optional existing session.
        """
        stmt = select(func.count()).select_from(DeviceEvent).where(
            DeviceEvent.risk_level.in_([RiskLevel.HIGH.value, RiskLevel.CRITICAL.value])
        )

        if session is not None:
            return session.scalar(stmt) or 0

        with get_db() as s:
            return s.scalar(stmt) or 0

    @classmethod
    def update_action(
        cls,
        session: Session,
        event_id: int,
        new_action: PolicyAction | str,
    ) -> Optional[DeviceEvent]:
        """Update the ``action_taken`` field on an existing event.

        Parameters
        ----------
        session:
            Active session.
        event_id:
            PK of the event to update.
        new_action:
            New ``PolicyAction`` to set.

        Returns
        -------
        DeviceEvent or None
            The updated event, or ``None`` if not found.
        """
        event = session.get(DeviceEvent, event_id)
        if event is None:
            return None

        action_val: str = (
            new_action.value if isinstance(new_action, PolicyAction) else new_action
        )
        event.action_taken = action_val
        session.flush()
        return event

    @classmethod
    def delete_event(cls, session: Session, event_id: int) -> bool:
        """Delete a ``DeviceEvent`` (and its cascaded children) by PK.

        Parameters
        ----------
        session:
            Active session.
        event_id:
            PK of the event to delete.

        Returns
        -------
        bool
            ``True`` if the row was found and deleted, ``False`` otherwise.
        """
        event = session.get(DeviceEvent, event_id)
        if event is None:
            return False
        session.delete(event)
        session.flush()
        return True


# ---------------------------------------------------------------------------
# FileScanRepository
# ---------------------------------------------------------------------------


class FileScanRepository:
    """CRUD operations for the ``FileScanResult`` table."""

    @classmethod
    def log_file_scan(
        cls,
        session: Session,
        *,
        device_event_id: int,
        file_path: str,
        file_name: str,
        file_size_bytes: Optional[int] = None,
        sha256_hash: Optional[str] = None,
        md5_hash: Optional[str] = None,
        is_malicious: bool = False,
        threat_name: Optional[str] = None,
        scan_engine: Optional[str] = None,
        risk_level: RiskLevel | str = RiskLevel.SAFE,
        is_simulated: bool = False,
        notes: Optional[str] = None,
    ) -> FileScanResult:
        """Create and persist a ``FileScanResult`` row.

        Parameters
        ----------
        session:
            Active SQLAlchemy session.
        device_event_id:
            FK to the parent ``DeviceEvent``.
        file_path:
            Full path on the device.
        file_name:
            Basename of the file.
        file_size_bytes:
            File size in bytes (optional).
        sha256_hash:
            SHA-256 hex digest.
        md5_hash:
            MD5 hex digest.
        is_malicious:
            True if the hash matched a threat signature.
        threat_name:
            Threat family name if malicious.
        scan_engine:
            Identifier and version string of the scan engine.
        risk_level:
            Risk level for this file.
        is_simulated:
            True in simulation mode.
        notes:
            Additional notes.

        Returns
        -------
        FileScanResult
            The newly created and flushed row.
        """
        risk_val: str = (
            risk_level.value if isinstance(risk_level, RiskLevel) else risk_level
        )

        result = FileScanResult(
            device_event_id=device_event_id,
            file_path=file_path,
            file_name=file_name,
            file_size_bytes=file_size_bytes,
            sha256_hash=sha256_hash,
            md5_hash=md5_hash,
            is_malicious=is_malicious,
            threat_name=threat_name,
            scan_engine=scan_engine,
            risk_level=risk_val,
            is_simulated=is_simulated,
            notes=notes,
            timestamp=datetime.now(timezone.utc),
        )
        session.add(result)
        session.flush()
        return result

    @classmethod
    def get_scans_for_event(
        cls,
        device_event_id: int,
        session: Optional[Session] = None,
    ) -> list[FileScanResult]:
        """Return all scan results linked to a device event.

        Parameters
        ----------
        device_event_id:
            PK of the parent ``DeviceEvent``.
        session:
            Optional existing session.
        """
        stmt = (
            select(FileScanResult)
            .where(FileScanResult.device_event_id == device_event_id)
            .order_by(desc(FileScanResult.timestamp))
        )

        if session is not None:
            return list(session.scalars(stmt).all())

        with get_db() as s:
            rows = list(s.scalars(stmt).all())
            for row in rows:
                s.expunge(row)
            return rows

    @classmethod
    def get_malicious_scans(
        cls,
        limit: int = 50,
        session: Optional[Session] = None,
    ) -> list[FileScanResult]:
        """Return the most recent malicious file scan results.

        Parameters
        ----------
        limit:
            Maximum rows to return.
        session:
            Optional existing session.
        """
        stmt = (
            select(FileScanResult)
            .where(FileScanResult.is_malicious.is_(True))
            .order_by(desc(FileScanResult.timestamp))
            .limit(limit)
        )

        if session is not None:
            return list(session.scalars(stmt).all())

        with get_db() as s:
            rows = list(s.scalars(stmt).all())
            for row in rows:
                s.expunge(row)
            return rows

    @classmethod
    def find_by_hash(
        cls,
        sha256_hash: str,
        session: Optional[Session] = None,
    ) -> list[FileScanResult]:
        """Look up all scan results that share the given SHA-256 hash.

        Useful for checking whether a specific file hash has been seen before.

        Parameters
        ----------
        sha256_hash:
            64-character hex digest to search for.
        session:
            Optional existing session.
        """
        stmt = select(FileScanResult).where(
            FileScanResult.sha256_hash == sha256_hash
        )

        if session is not None:
            return list(session.scalars(stmt).all())

        with get_db() as s:
            rows = list(s.scalars(stmt).all())
            for row in rows:
                s.expunge(row)
            return rows


# ---------------------------------------------------------------------------
# UserActionRepository
# ---------------------------------------------------------------------------


class UserActionRepository:
    """CRUD operations for the ``UserAction`` audit-log table."""

    @classmethod
    def log_action(
        cls,
        session: Session,
        *,
        device_event_id: int,
        action: PolicyAction | str,
        operator_id: Optional[str] = None,
        reason: Optional[str] = None,
        was_override: bool = False,
        previous_action: Optional[PolicyAction | str] = None,
        ip_address: Optional[str] = None,
        notes: Optional[str] = None,
    ) -> UserAction:
        """Record an operator action against a device event.

        Parameters
        ----------
        session:
            Active SQLAlchemy session.
        device_event_id:
            FK to the affected ``DeviceEvent``.
        action:
            The policy action chosen by the operator.
        operator_id:
            Operator username or PIN-hash prefix.
        reason:
            Justification text.
        was_override:
            True if this action overrides an automatic decision.
        previous_action:
            The automatic action that was overridden.
        ip_address:
            Source IP for remote admin audit trail.
        notes:
            Free-text notes.

        Returns
        -------
        UserAction
            The newly created and flushed ``UserAction`` row.
        """
        action_val: str = (
            action.value if isinstance(action, PolicyAction) else action
        )
        prev_val: Optional[str] = None
        if previous_action is not None:
            prev_val = (
                previous_action.value
                if isinstance(previous_action, PolicyAction)
                else previous_action
            )

        user_action = UserAction(
            device_event_id=device_event_id,
            action=action_val,
            operator_id=operator_id,
            reason=reason,
            was_override=was_override,
            previous_action=prev_val,
            ip_address=ip_address,
            notes=notes,
            timestamp=datetime.now(timezone.utc),
        )
        session.add(user_action)
        session.flush()
        return user_action

    @classmethod
    def get_actions_for_event(
        cls,
        device_event_id: int,
        session: Optional[Session] = None,
    ) -> list[UserAction]:
        """Return all user actions linked to a given device event.

        Parameters
        ----------
        device_event_id:
            PK of the parent ``DeviceEvent``.
        session:
            Optional existing session.
        """
        stmt = (
            select(UserAction)
            .where(UserAction.device_event_id == device_event_id)
            .order_by(desc(UserAction.timestamp))
        )

        if session is not None:
            return list(session.scalars(stmt).all())

        with get_db() as s:
            rows = list(s.scalars(stmt).all())
            for row in rows:
                s.expunge(row)
            return rows

    @classmethod
    def get_recent_actions(
        cls,
        limit: int = 20,
        session: Optional[Session] = None,
    ) -> list[UserAction]:
        """Return the most recent user actions across all device events.

        Parameters
        ----------
        limit:
            Maximum number of rows to return.
        session:
            Optional existing session.
        """
        stmt = (
            select(UserAction)
            .order_by(desc(UserAction.timestamp))
            .limit(limit)
        )

        if session is not None:
            return list(session.scalars(stmt).all())

        with get_db() as s:
            rows = list(s.scalars(stmt).all())
            for row in rows:
                s.expunge(row)
            return rows


# ---------------------------------------------------------------------------
# AlertRepository
# ---------------------------------------------------------------------------


class AlertRepository:
    """CRUD operations for the ``SystemAlert`` table."""

    @classmethod
    def create_alert(
        cls,
        session: Session,
        *,
        title: str,
        message: str,
        severity: AlertSeverity | str = AlertSeverity.INFO,
        category: AlertCategory | str = AlertCategory.SYSTEM,
        device_event_id: Optional[int] = None,
        is_simulated: bool = False,
        source: Optional[str] = None,
    ) -> SystemAlert:
        """Create a new ``SystemAlert`` row.

        Parameters
        ----------
        session:
            Active SQLAlchemy session.
        title:
            Short alert title shown in the notification area.
        message:
            Full alert body text.
        severity:
            ``AlertSeverity`` level.
        category:
            ``AlertCategory`` functional area.
        device_event_id:
            Optional FK to a related ``DeviceEvent``.
        is_simulated:
            True in simulation mode.
        source:
            Name of the subsystem raising this alert.

        Returns
        -------
        SystemAlert
            The newly created and flushed ``SystemAlert`` row.
        """
        sev_val: str = (
            severity.value if isinstance(severity, AlertSeverity) else severity
        )
        cat_val: str = (
            category.value if isinstance(category, AlertCategory) else category
        )

        alert = SystemAlert(
            title=title,
            message=message,
            severity=sev_val,
            category=cat_val,
            device_event_id=device_event_id,
            is_simulated=is_simulated,
            source=source,
            timestamp=datetime.now(timezone.utc),
        )
        session.add(alert)
        session.flush()
        return alert

    @classmethod
    def get_unread_alerts(
        cls,
        limit: int = 50,
        session: Optional[Session] = None,
    ) -> list[SystemAlert]:
        """Return unread alerts, newest first.

        Parameters
        ----------
        limit:
            Maximum number of rows to return.
        session:
            Optional existing session.
        """
        stmt = (
            select(SystemAlert)
            .where(
                SystemAlert.is_read.is_(False),
                SystemAlert.is_dismissed.is_(False),
            )
            .order_by(desc(SystemAlert.timestamp))
            .limit(limit)
        )

        if session is not None:
            return list(session.scalars(stmt).all())

        with get_db() as s:
            rows = list(s.scalars(stmt).all())
            for row in rows:
                s.expunge(row)
            return rows

    @classmethod
    def mark_as_read(
        cls,
        session: Session,
        alert_id: int,
    ) -> Optional[SystemAlert]:
        """Mark a single alert as read.

        Parameters
        ----------
        session:
            Active session.
        alert_id:
            PK of the alert.

        Returns
        -------
        SystemAlert or None
        """
        alert = session.get(SystemAlert, alert_id)
        if alert is None:
            return None
        alert.is_read = True
        session.flush()
        return alert

    @classmethod
    def mark_all_as_read(cls, session: Session) -> int:
        """Mark all unread, non-dismissed alerts as read.

        Parameters
        ----------
        session:
            Active session.

        Returns
        -------
        int
            Number of alerts updated.
        """
        stmt = (
            select(SystemAlert)
            .where(
                SystemAlert.is_read.is_(False),
                SystemAlert.is_dismissed.is_(False),
            )
        )
        alerts: list[SystemAlert] = list(session.scalars(stmt).all())
        for alert in alerts:
            alert.is_read = True
        session.flush()
        return len(alerts)

    @classmethod
    def dismiss_alert(
        cls,
        session: Session,
        alert_id: int,
    ) -> Optional[SystemAlert]:
        """Dismiss a single alert from the UI notification centre.

        Parameters
        ----------
        session:
            Active session.
        alert_id:
            PK of the alert.
        """
        alert = session.get(SystemAlert, alert_id)
        if alert is None:
            return None
        alert.is_dismissed = True
        session.flush()
        return alert

    @classmethod
    def get_recent_alerts(
        cls,
        limit: int = 20,
        session: Optional[Session] = None,
    ) -> list[SystemAlert]:
        """Return recent alerts (read and unread), newest first.

        Parameters
        ----------
        limit:
            Maximum rows to return.
        session:
            Optional existing session.
        """
        stmt = (
            select(SystemAlert)
            .order_by(desc(SystemAlert.timestamp))
            .limit(limit)
        )

        if session is not None:
            return list(session.scalars(stmt).all())

        with get_db() as s:
            rows = list(s.scalars(stmt).all())
            for row in rows:
                s.expunge(row)
            return rows

    @classmethod
    def get_unread_count(cls, session: Optional[Session] = None) -> int:
        """Return the count of unread, non-dismissed alerts.

        Parameters
        ----------
        session:
            Optional existing session.
        """
        stmt = select(func.count()).select_from(SystemAlert).where(
            SystemAlert.is_read.is_(False),
            SystemAlert.is_dismissed.is_(False),
        )

        if session is not None:
            return session.scalar(stmt) or 0

        with get_db() as s:
            return s.scalar(stmt) or 0
